use std::collections::BTreeMap;

use crate::{ActionDefinition, ActionType, SideEffectLevel};

pub fn action_registry() -> BTreeMap<ActionType, ActionDefinition> {
    BTreeMap::from([
        definition(
            ActionType::AnswerDirectly,
            "Answer from currently available context.",
            vec![],
            SideEffectLevel::None,
            "full",
            "low_tokens",
            "medium_hallucination",
            false,
            "response",
            None,
        ),
        definition(
            ActionType::SearchWeb,
            "Search public web sources for fresh or missing jurisdiction_evidence.",
            vec!["network_read"],
            SideEffectLevel::ExternalReversible,
            "full",
            "medium_external",
            "medium_source_quality",
            false,
            "external_retrieval",
            Some("freshness_required"),
        ),
        definition(
            ActionType::RetrieveContext,
            "Retrieve local context from a configured retrieval index.",
            vec!["retrieval_read"],
            SideEffectLevel::None,
            "full",
            "medium_context",
            "low_source_quality",
            false,
            "local_retrieval",
            Some("retrieval_available"),
        ),
        definition(
            ActionType::ReadFile,
            "Read a local, uploaded, or user-provided file.",
            vec!["file_read"],
            SideEffectLevel::None,
            "full",
            "medium_context",
            "low_privacy",
            false,
            "local_io",
            Some("file_available"),
        ),
        definition(
            ActionType::InspectCode,
            "Inspect repository files or search code without executing it.",
            vec!["file_read"],
            SideEffectLevel::None,
            "full",
            "medium_context",
            "low_privacy",
            false,
            "local_io",
            Some("repo_available"),
        ),
        definition(
            ActionType::ExecuteCode,
            "Execute a local command directly through the host process.",
            vec!["code_execute"],
            SideEffectLevel::LocalPersistent,
            "partial",
            "high_compute",
            "high_tool_risk",
            true,
            "local_execution",
            Some("allow_direct_execution"),
        ),
        definition(
            ActionType::CallTool,
            "Invoke a configured local command or HTTP tool.",
            vec!["tool_call"],
            SideEffectLevel::ExternalReversible,
            "partial",
            "medium_external",
            "high_tool_risk",
            true,
            "tool",
            Some("tool_call_requested"),
        ),
        definition(
            ActionType::AskUser,
            "Ask the user for missing information or approval.",
            vec![],
            SideEffectLevel::None,
            "full",
            "high_attention",
            "low",
            false,
            "human",
            Some("ambiguous"),
        ),
        definition(
            ActionType::StoreMemory,
            "Persist a durable memory candidate.",
            vec!["memory_write"],
            SideEffectLevel::LocalPersistent,
            "partial",
            "medium_memory_bloat",
            "high_privacy",
            true,
            "memory",
            Some("memory_candidate_value"),
        ),
        definition(
            ActionType::EscalateModel,
            "Escalate to a stronger or more expensive model.",
            vec!["model_escalate"],
            SideEffectLevel::ExternalReversible,
            "full",
            "high_money",
            "medium_privacy",
            false,
            "model",
            Some("high_uncertainty"),
        ),
        definition(
            ActionType::ConciergeReview,
            "Escalate to Velvet Concierge for safety or policy reasons.",
            vec![],
            SideEffectLevel::None,
            "full",
            "max_attention",
            "low",
            false,
            "concierge",
            Some("requires_concierge_review"),
        ),
    ])
}

pub fn get_action_definition(action_type: ActionType) -> ActionDefinition {
    action_registry()
        .remove(&action_type)
        .expect("all built-in actions have registry definitions")
}

#[allow(clippy::too_many_arguments)]
fn definition(
    action_type: ActionType,
    description: &str,
    permissions: Vec<&str>,
    side_effect_level: SideEffectLevel,
    reversibility: &str,
    default_cost_class: &str,
    default_risk_class: &str,
    requires_user_approval: bool,
    action_family: &str,
    availability_key: Option<&str>,
) -> (ActionType, ActionDefinition) {
    (
        action_type,
        ActionDefinition {
            action_type,
            description: description.to_string(),
            permissions: permissions.into_iter().map(ToString::to_string).collect(),
            side_effect_level,
            reversibility: reversibility.to_string(),
            default_cost_class: default_cost_class.to_string(),
            default_risk_class: default_risk_class.to_string(),
            requires_user_approval,
            action_family: action_family.to_string(),
            availability_key: availability_key.map(ToString::to_string),
        },
    )
}
