"""Velvet Rust-backed SDK."""

from pathlib import Path

__version__ = "1.0.0"

from velvet.actions import (
    AuthorityClass,
    CanonicalAction,
    MaskedActionFailure,
    MutationKind,
    ProofDecision,
    Reversibility,
)
from velvet.admission import (
    UnifiedAdmissionDecision,
    UnifiedAdmissionDecisionType,
    UnifiedAdmissionReason,
)
from velvet.admission_evidence import (
    RawActionArtifactRef,
    admission_evidence_hash,
    build_admission_evidence,
    validate_admission_evidence,
    verify_admission_evidence,
    verify_raw_action_ref,
    write_raw_action_artifact,
)
from velvet.agent_registry import (
    AgentRecord,
    AgentRegistry,
    AgentStatus,
    AgentToolBinding,
    ApprovalTier,
    RegistryFinding,
    SchemaStatus,
    ToolSurface,
    ToolSurfaceKind,
    schema_hash_for_input_schema,
)
from velvet.appraisal import AppraisalEngine, AppraisalResult
from velvet.approvals import (
    ApprovalReceipt,
    ApprovalRequest,
    ApprovalSnapshot,
    ApprovalStatus,
    ApprovalStore,
)
from velvet.budget_safety import (
    DEFAULT_DETERMINISTIC_BUDGET_THEOREM_REFS,
    DEFAULT_DETERMINISTIC_OBLIGATIONS,
    DEFAULT_PROBABILISTIC_BUDGET_THEOREM_REFS,
    DEFAULT_PROBABILISTIC_OBLIGATIONS,
    BudgetSafetyLedgerStore,
    DeterministicBudgetSpec,
    ProbabilisticBudgetSpec,
    budget_action_hash,
    budget_ledger_hash,
    build_cgf_ville_budget_certificate,
    build_deterministic_budget_certificate,
    build_moment_cantelli_budget_certificate,
    cgf_ville_high_probability_bound,
    conservative_utf8_token_upper_bound,
    filtration_hash_for_state,
    is_certifying,
    is_probabilistic_certifying,
    make_budget_ledger,
    microusd_to_usd_display,
    moment_cantelli_high_probability_bound,
    openai_responses_hard_cap_usd,
    openai_responses_realized_cost_usd,
    slack_microusd_to_usd_display,
    usd_to_microusd_ceil_or_reject,
    usd_to_microusd_exact_or_reject,
    with_recomputed_ledger_hash,
)
from velvet.composition import (
    CertificateComposition,
    compose_conditional_continuation,
    compose_parallel_certificates,
    compose_sequential_certificates,
    composite_upper_bound,
)
from velvet.contracts import AdmissionContract
from velvet.evidence import (
    build_evidence_pack,
    render_evidence_pack_markdown,
    verify_evidence_manifest,
)
from velvet.execution import (
    AuthorizedExecution,
    ExecutionPermit,
    ExecutionReceipt,
    PermitClaimStore,
    PermitValidationContext,
    PreparedExecution,
    VelvetExecutor,
    build_pre_execution_record,
    prepare_execution,
    strip_model_controlled_execution_metadata,
    verification_status,
    verify_execution_permit,
    verify_execution_receipt,
)
from velvet.executor import AdmissionOutcome, VelvetAdmissionLayer
from velvet.fallback import VelvetFallback, VelvetFallbackCompiler
from velvet.frontier import AdmissionFrontier, build_admission_frontier
from velvet.gateway import (
    CallableDispatcher,
    InlineDispatcher,
    InlineDispatchReceipt,
    InlineGateway,
    InlineGatewayDecision,
    InlineGatewayRequest,
    InlineGatewayResult,
)
from velvet.ledger import (
    AuthorityLedger,
    DenialPressure,
    VelvetLedger,
    build_ledger_segment_manifest,
    build_velvet_ledger_report,
    read_ledger_records,
    render_velvet_ledger_markdown,
    seal_thread_decision,
    validate_ledger_file,
    validate_thread_file,
    verify_velvet_ledger,
)
from velvet.max_de import (
    BetaBernoulliPosteriorSpec,
    DirichletCategoricalPosteriorSpec,
    build_beta_bernoulli_certificate,
    build_dirichlet_categorical_certificate,
    build_reserve_priced_beta_bernoulli_certificate,
    certified_beta_bernoulli_candidate,
    certified_dirichlet_categorical_candidate,
)
from velvet.max_de import (
    GammaRateAdmissionDecision as GammaRateAdmissionDecision,
)
from velvet.max_de import (
    GammaRateBounds as GammaRateBounds,
)
from velvet.max_de import (
    GammaRateCertificate as GammaRateCertificate,
)
from velvet.max_de import (
    GammaRateCertificateMethod as GammaRateCertificateMethod,
)
from velvet.max_de import (
    GammaRateMonteCarloLCB as GammaRateMonteCarloLCB,
)
from velvet.max_de import (
    GammaRatePositivePartMoments as GammaRatePositivePartMoments,
)
from velvet.max_de import (
    GammaRatePosteriorSpec as GammaRatePosteriorSpec,
)
from velvet.max_de import (
    certified_gamma_rate_candidate as certified_gamma_rate_candidate,
)
from velvet.mcp import DirectVelvetMCPAdapter
from velvet.memory import MemoryEngine
from velvet.normalizer import VelvetActionNormalizer
from velvet.ops import build_control_plane_snapshot
from velvet.policy_bundle import (
    DEFAULT_POLICY_BUNDLE_SIGNING_KEY,
    DEMO_POLICY_BUNDLE_SIGNING_KEY,
    DEMO_POLICY_BUNDLE_SIGNING_KEY_ID,
    POLICY_BUNDLE_SCHEMA_VERSION,
    PolicyBundleError,
    PolicyBundleExpired,
    PolicyBundleInvalid,
    PolicyBundleMissing,
    PolicyBundleTampered,
    VerifiedPolicyBundle,
    compute_policy_hash,
    load_policy_bundle,
    sign_policy_bundle,
    verify_policy_bundle,
    write_signed_policy_bundle,
)
from velvet.policy_simulation import (
    PolicySimulationDelta,
    PolicySimulationReport,
    render_policy_simulation_markdown,
    simulate_policy,
)
from velvet.replay import ReplayResult, run_replay
from velvet.rope import (
    AdmissionDecision,
    RopeRun,
    ToolRiskClass,
    VelvetMCP,
    VelvetRope,
    VelvetToolCall,
    VelvetToolPolicy,
    VelvetWarrant,
    mcp_tool_key,
)
from velvet.router import Router
from velvet.sandbox import SandboxConfig
from velvet.signing import (
    ArtifactSigner,
    AwsKmsSigner,
    Ed25519PublicVerifier,
    Ed25519SigningProvider,
    LocalDevHmacSigner,
    LocalEd25519Signer,
    SignatureBlock,
    SignatureRecord,
    SigningConfigurationError,
    SigningError,
    SigningProvider,
    SigningProviderNotConfigured,
    VaultTransitSigner,
    aws_kms_signer_from_boto3,
    default_demo_signer,
    generate_ed25519_keypair,
    load_demo_ed25519_signer,
    resolve_ed25519_signing_provider,
    resolve_signing_provider,
    sign_payload_hash,
    vault_transit_signer_from_hvac,
    verify_signature_record,
)
from velvet.storage import (
    ArtifactRef,
    EvidenceManifest,
    EvidenceStore,
    LocalFilesystemEvidenceStore,
    LocalManifestSigner,
    ManifestSigner,
    S3CompatibleEvidenceStore,
    VerificationResult,
)
from velvet.types import (
    ActionDefinition,
    ActionMutation,
    ActionType,
    AdmissionConstraintResult,
    AdmissionScore,
    AdmissionTrace,
    BudgetCertificate,
    BudgetCertificateKind,
    BudgetOutcome,
    BudgetSafetyLedger,
    BudgetScope,
    BudgetState,
    BudgetTrace,
    CandidateAction,
    CandidateSource,
    CapabilityClass,
    CapProvenance,
    CertificateEffect,
    CertificateEvidence,
    CertificateOutcome,
    CompensatorStep,
    CompetitorResult,
    ConcurrencyModel,
    ConstraintSeverity,
    ContainerRuntime,
    CostBound,
    CostVector,
    DataClass,
    DecisionType,
    DeterministicBudgetCertificate,
    EffectVector,
    EgressRule,
    Evidence,
    ExecutionResult,
    ExecutionStatus,
    LatencyBound,
    MemoryDecision,
    MountMode,
    MountSpec,
    NetworkPolicy,
    ObjectiveComponents,
    OutputTransform,
    PolicyContext,
    PolicyDecision,
    PolicyReason,
    PolicyTraceEntry,
    PricingBreakdown,
    PricingPolicy,
    ProbabilisticBudgetCertificate,
    ResourceLimits,
    RiskVector,
    RouteRunResult,
    RoutingDecision,
    RuntimeMode,
    SandboxBackendKind,
    SandboxedCommand,
    SandboxExecutionPlan,
    SandboxProvenance,
    SandboxViolation,
    SourceToSinkFlow,
    ThreadRecord,
    TypedReversibility,
    TypedSideEffectClass,
    UtilityBound,
    WriteFootprint,
)
from velvet.vc_demo import build_vc_demo_payload, render_vc_demo_markdown
from velvet.workflows import WorkflowRun, WorkflowRunner


def run_liability_benchmark(
    output_dir: str | Path = "reports/liability",
    *,
    include_cloud: bool = False,
    suite: str = "liability",
    live_competitors: bool | str = False,
) -> object:
    from velvet.liability_benchmark import run_liability_benchmark as _run_liability_benchmark

    return _run_liability_benchmark(
        output_dir,
        include_cloud=include_cloud,
        suite=suite,
        live_competitors=live_competitors,
    )


__all__ = [
    "ActionDefinition",
    "ActionMutation",
    "AdmissionContract",
    "AdmissionConstraintResult",
    "AdmissionFrontier",
    "AdmissionOutcome",
    "AdmissionTrace",
    "AppraisalEngine",
    "AppraisalResult",
    "AgentRecord",
    "AgentRegistry",
    "AgentStatus",
    "AgentToolBinding",
    "ApprovalRequest",
    "ApprovalReceipt",
    "ApprovalSnapshot",
    "ApprovalStatus",
    "ApprovalStore",
    "ApprovalTier",
    "ArtifactRef",
    "ArtifactSigner",
    "AwsKmsSigner",
    "aws_kms_signer_from_boto3",
    "AuthorityClass",
    "AuthorityLedger",
    "VelvetWarrant",
    "ActionType",
    "VelvetRope",
    "BudgetState",
    "BudgetCertificate",
    "BudgetCertificateKind",
    "BudgetOutcome",
    "BudgetSafetyLedger",
    "BudgetSafetyLedgerStore",
    "BudgetScope",
    "BudgetTrace",
    "BetaBernoulliPosteriorSpec",
    "CandidateAction",
    "CandidateSource",
    "CanonicalAction",
    "CapabilityClass",
    "CertificateComposition",
    "CertificateEffect",
    "CertificateEvidence",
    "CertificateOutcome",
    "CapProvenance",
    "CompensatorStep",
    "ConcurrencyModel",
    "CompetitorResult",
    "ContainerRuntime",
    "ConstraintSeverity",
    "CostBound",
    "CostVector",
    "DataClass",
    "DEFAULT_POLICY_BUNDLE_SIGNING_KEY",
    "DEMO_POLICY_BUNDLE_SIGNING_KEY",
    "DEMO_POLICY_BUNDLE_SIGNING_KEY_ID",
    "DecisionType",
    "DenialPressure",
    "DeterministicBudgetCertificate",
    "DeterministicBudgetSpec",
    "DirichletCategoricalPosteriorSpec",
    "DirectVelvetMCPAdapter",
    "EgressRule",
    "Evidence",
    "EvidenceManifest",
    "EvidenceStore",
    "ExecutionResult",
    "ExecutionPermit",
    "ExecutionReceipt",
    "ExecutionStatus",
    "EffectVector",
    "AuthorizedExecution",
    "PermitClaimStore",
    "PermitValidationContext",
    "PreparedExecution",
    "strip_model_controlled_execution_metadata",
    "InlineDispatchReceipt",
    "InlineDispatcher",
    "InlineGateway",
    "InlineGatewayDecision",
    "InlineGatewayRequest",
    "InlineGatewayResult",
    "AdmissionDecision",
    "RopeRun",
    "AdmissionScore",
    "RawActionArtifactRef",
    "LocalFilesystemEvidenceStore",
    "LocalDevHmacSigner",
    "Ed25519PublicVerifier",
    "Ed25519SigningProvider",
    "LocalEd25519Signer",
    "LocalManifestSigner",
    "LatencyBound",
    "MemoryDecision",
    "MemoryEngine",
    "MaskedActionFailure",
    "ManifestSigner",
    "MutationKind",
    "VelvetMCP",
    "ToolRiskClass",
    "VelvetToolCall",
    "VelvetToolPolicy",
    "MountMode",
    "MountSpec",
    "NetworkPolicy",
    "ObjectiveComponents",
    "OutputTransform",
    "POLICY_BUNDLE_SCHEMA_VERSION",
    "PolicyDecision",
    "PolicyContext",
    "PolicyReason",
    "PolicyBundleError",
    "PolicyBundleExpired",
    "PolicyBundleInvalid",
    "PolicyBundleMissing",
    "PolicyBundleTampered",
    "PolicySimulationDelta",
    "PolicySimulationReport",
    "PolicyTraceEntry",
    "ProofDecision",
    "PricingBreakdown",
    "PricingPolicy",
    "ProbabilisticBudgetCertificate",
    "VelvetLedger",
    "ResourceLimits",
    "ReplayResult",
    "Reversibility",
    "RiskVector",
    "RouteRunResult",
    "Router",
    "RuntimeMode",
    "RoutingDecision",
    "RegistryFinding",
    "SchemaStatus",
    "SandboxBackendKind",
    "SandboxConfig",
    "SandboxExecutionPlan",
    "SandboxProvenance",
    "SandboxViolation",
    "SandboxedCommand",
    "S3CompatibleEvidenceStore",
    "SourceToSinkFlow",
    "SignatureBlock",
    "SignatureRecord",
    "SigningConfigurationError",
    "SigningError",
    "SigningProvider",
    "SigningProviderNotConfigured",
    "ThreadRecord",
    "TypedReversibility",
    "TypedSideEffectClass",
    "ToolSurface",
    "ToolSurfaceKind",
    "UtilityBound",
    "UnifiedAdmissionDecision",
    "UnifiedAdmissionDecisionType",
    "UnifiedAdmissionReason",
    "CallableDispatcher",
    "VerifiedPolicyBundle",
    "VelvetAdmissionLayer",
    "VelvetActionNormalizer",
    "VelvetExecutor",
    "VelvetFallback",
    "VelvetFallbackCompiler",
    "VerificationResult",
    "WorkflowRun",
    "WorkflowRunner",
    "WriteFootprint",
    "build_ledger_segment_manifest",
    "build_control_plane_snapshot",
    "build_admission_frontier",
    "build_beta_bernoulli_certificate",
    "build_cgf_ville_budget_certificate",
    "build_deterministic_budget_certificate",
    "build_dirichlet_categorical_certificate",
    "build_moment_cantelli_budget_certificate",
    "build_reserve_priced_beta_bernoulli_certificate",
    "compose_conditional_continuation",
    "compose_parallel_certificates",
    "compose_sequential_certificates",
    "composite_upper_bound",
    "cgf_ville_high_probability_bound",
    "is_certifying",
    "is_probabilistic_certifying",
    "build_evidence_pack",
    "build_admission_evidence",
    "build_pre_execution_record",
    "build_velvet_ledger_report",
    "read_ledger_records",
    "build_vc_demo_payload",
    "compute_policy_hash",
    "admission_evidence_hash",
    "load_policy_bundle",
    "validate_admission_evidence",
    "verify_admission_evidence",
    "verify_raw_action_ref",
    "write_raw_action_artifact",
    "mcp_tool_key",
    "render_evidence_pack_markdown",
    "render_policy_simulation_markdown",
    "seal_thread_decision",
    "render_vc_demo_markdown",
    "render_velvet_ledger_markdown",
    "run_replay",
    "run_liability_benchmark",
    "default_demo_signer",
    "generate_ed25519_keypair",
    "load_demo_ed25519_signer",
    "resolve_ed25519_signing_provider",
    "resolve_signing_provider",
    "sign_payload_hash",
    "sign_policy_bundle",
    "simulate_policy",
    "prepare_execution",
    "validate_ledger_file",
    "validate_thread_file",
    "verify_evidence_manifest",
    "verify_policy_bundle",
    "verify_velvet_ledger",
    "verify_signature_record",
    "verification_status",
    "verify_execution_permit",
    "verify_execution_receipt",
    "VaultTransitSigner",
    "vault_transit_signer_from_hvac",
    "write_signed_policy_bundle",
    "certified_beta_bernoulli_candidate",
    "certified_dirichlet_categorical_candidate",
    "budget_action_hash",
    "budget_ledger_hash",
    "conservative_utf8_token_upper_bound",
    "filtration_hash_for_state",
    "make_budget_ledger",
    "microusd_to_usd_display",
    "moment_cantelli_high_probability_bound",
    "openai_responses_hard_cap_usd",
    "openai_responses_realized_cost_usd",
    "slack_microusd_to_usd_display",
    "usd_to_microusd_ceil_or_reject",
    "usd_to_microusd_exact_or_reject",
    "schema_hash_for_input_schema",
    "with_recomputed_ledger_hash",
    "DEFAULT_DETERMINISTIC_BUDGET_THEOREM_REFS",
    "DEFAULT_DETERMINISTIC_OBLIGATIONS",
    "DEFAULT_PROBABILISTIC_BUDGET_THEOREM_REFS",
    "DEFAULT_PROBABILISTIC_OBLIGATIONS",
    "ProbabilisticBudgetSpec",
]
