"""Research reproductions for Velvet experiments."""

from velvet.research.actual_kernel import (
    BernoulliState,
    BetaPosterior,
    Transition,
    candidate_excluded_baseline,
    enumerate_transitions,
    host_arm,
    host_delta_override,
    host_override_probabilities,
    kernel_expectation,
    moving_certificate,
)
from velvet.research.anchor_tail import (
    LogChernoffResult,
    ProductAnchorTailBound,
    beta_anchor_drop_log_bound,
    beta_negative_mgf,
    product_anchor_drop_log_bound,
)
from velvet.research.bernoulli import BernoulliBandit, BetaBernoulliPosterior, CompensatorStep
from velvet.research.beta_ei import beta_expected_improvement, beta_mean, beta_upper_tail
from velvet.research.crossing_dp import (
    crossing_indicator,
    finite_horizon_crossing_probability,
    rescue_indicator,
)
from velvet.research.dirichlet_categorical import (
    DirichletCategoricalPosterior,
    DirichletLowerCertificateDetails,
)
from velvet.research.gamma_rate import (
    GammaRateAdmissionDecision,
    GammaRateBounds,
    GammaRateCertificate,
    GammaRateCertificateMethod,
    GammaRateMonteCarloLCB,
    GammaRatePositivePartMoments,
    GammaRatePosteriorSpec,
    certified_gamma_rate_candidate,
    deterministic_one_step_lower_certificate,
    gamma_rate_bounds,
    gamma_rate_tail_first_moment,
    gamma_rate_tail_probability,
    gamma_rate_tail_second_moment,
    l2_fallback_upper_certificate,
    l2_upper_certificate,
    m_v_plus,
    monte_carlo_lcb,
    positive_part_moments,
    q_v_plus,
    s_v_plus,
)
from velvet.research.policies import (
    CertifiedMaxDEPolicy,
    DelightGatedPolicy,
    EpsilonGreedyPolicy,
    ThompsonSamplingPolicy,
)

__all__ = [
    "BernoulliState",
    "BernoulliBandit",
    "BetaBernoulliPosterior",
    "BetaPosterior",
    "CertifiedMaxDEPolicy",
    "CompensatorStep",
    "DelightGatedPolicy",
    "DirichletCategoricalPosterior",
    "DirichletLowerCertificateDetails",
    "EpsilonGreedyPolicy",
    "GammaRateAdmissionDecision",
    "GammaRateBounds",
    "GammaRateCertificate",
    "GammaRateCertificateMethod",
    "GammaRateMonteCarloLCB",
    "GammaRatePositivePartMoments",
    "GammaRatePosteriorSpec",
    "LogChernoffResult",
    "ProductAnchorTailBound",
    "ThompsonSamplingPolicy",
    "Transition",
    "beta_anchor_drop_log_bound",
    "beta_expected_improvement",
    "beta_mean",
    "beta_negative_mgf",
    "beta_upper_tail",
    "candidate_excluded_baseline",
    "certified_gamma_rate_candidate",
    "crossing_indicator",
    "deterministic_one_step_lower_certificate",
    "enumerate_transitions",
    "finite_horizon_crossing_probability",
    "rescue_indicator",
    "gamma_rate_bounds",
    "gamma_rate_tail_first_moment",
    "gamma_rate_tail_probability",
    "gamma_rate_tail_second_moment",
    "host_arm",
    "host_delta_override",
    "host_override_probabilities",
    "kernel_expectation",
    "l2_fallback_upper_certificate",
    "l2_upper_certificate",
    "m_v_plus",
    "moving_certificate",
    "monte_carlo_lcb",
    "positive_part_moments",
    "product_anchor_drop_log_bound",
    "q_v_plus",
    "s_v_plus",
]
